name: Compile Latex and publish

on:
  push:
    tags:
      - 'commit-*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    container:
      image: texlive/texlive:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile to latex
        run: |
          python3 compile.py
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-pdf
          path: main.pdf

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "Automated release of the compiled PDF."
          draft: false
          prerelease: false

      - name: Upload PDF to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./main.pdf
          asset_name: main.pdf
          asset_content_type: application/pdf
